### PR TITLE
Fix problems with User profile and firebase

### LINKED ISSUE #165: Fix design(null profile instead of null values, ...) problems with firebase and the user profiles

### PR DESCRIPTION
**Pull request by asfoury**

### CODE REVIEW

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 1]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
+    public fun getProfile(
+        onSuccess: (profile: ImmutableProfile?) -> Unit,
+        onFailure: (Exception) -> kotlin.Unit
+    ) {
         val userUid = getUser()?.uid
         if (userUid != null) {
             val docRef = firestore.collection(ROOT).document(userUid)
             docRef.get()
                 .addOnSuccessListener { document ->
                     if (document != null) {
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:82]: If the document is null, the code won't call any callback here (success with null or failure)

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 2]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
                         }
-
-                    } else {
-                        Log.d(TAG, "No such document")
                     }
                 }
                 .addOnFailureListener { exception ->
-                    Log.d(TAG, "get failed with ", exception)
+                    onFailure(exception)
                 }
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: This can be reduce to this : 
`.addOnFailureListener(onFailure)`

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 3]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
+                        val lastName = (document["firstName"] as? String)
+                        val age = (document["age"] as? Long)?.toInt()
+                        val sciper = (document["sciper"] as? Long)?.toInt()
+                        val phoneNumber = (document["phoneNumber"] as? String)
 
-                        val gender = when (document["gender"] as? String) {
+                        val gender = when ((document["gender"] as? String)) {
                             Gender.MALE.name -> Gender.MALE
                             Gender.FEMALE.name -> Gender.FEMALE
                             else -> Gender.OTHER
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:92]: If the field of gender is null or invalid, this line will return it as Gender.OTHER.
Should an invalid gender be equals to OTHER ?

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 4]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
                         }
-                        val phoneNumber = document["phoneNumber"] as? String
-                        val roleString = document["role"] as? String
-                        val sciperLong = document["sciper"]
 
-                        val role = when (roleString) {
+                        val role = when (document["role"] as? String) {
                             Role.TEACHER.name -> Role.TEACHER
                             Role.STUDENT.name -> Role.STUDENT
                             else -> Role.OTHER
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:98]: If the field of role is null or invalid, this line will return it as Role.OTHER.
Should an invalid role be equals to OTHER ?

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 5]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
+                            )) {
+                                is Success -> {
+                                    onSuccess(resProfile.value)
+                                }
+                                is Failure -> {
+                                    onFailure(Exception("Failure reason : ${resProfile.reason}"))
+                                }
                             }
+                        } else {
+                            onFailure(Exception("At least one of the following fields is null: firstName = $firstName, lastName = $lastName, age = $age, sciper = $sciper, phoneNumber = $phoneNumber."))
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:119]: Extracting messages to strings.xml could be better.
getString can be used with parameters (such as %s text, %d for number)

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 6]
```diff
@@ -59,69 +65,63 @@ class UserProfileDatabase(
...
+     * Gets the user profile from firebase if it exists
+     * @param onSuccess the closure that's when a profile is downloaded successfully with the fetched profile passed to it
+     * @param onFailure the closure that's called if the download fails
+     */
+    public fun getProfile(
+        onSuccess: (profile: ImmutableProfile?) -> Unit,
+        onFailure: (Exception) -> kotlin.Unit
+    ) {
         val userUid = getUser()?.uid
         if (userUid != null) {
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:78]: If the userUid is null, the code won't call the onFailure callback.

**Review by arnauds5 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 4 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:98]: Yes

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 3 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:92]: Yes

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 2 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: I agree!

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 6 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:78]: I added the call to onFailure in an else case

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 1 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:82]: I added the call to onFailure in an else case

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 5 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt:119]: strings.xml is main usage is to translate between the different languages the app will be deployed in, so in this specific case it does not make sense to add it to strings.xml.

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 7]
```diff
@@ -55,74 +61,68 @@ class UserProfileDatabase(
...
             val docRef = firestore.collection(ROOT).document(userUid)
             docRef.get()
                 .addOnSuccessListener { document ->
                     if (document != null) {
-                        val firstName = document["firstName"] as? String
-                        val lastName = document["lastName"] as? String
-                        val ageLong = document["age"]
+                        val firstName = (document["firstName"] as? String)
+                        val lastName = (document["firstName"] as? String)
```
Comment (arnauds5) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: There was a typo
```suggestion
                        val lastName = (document["lastName"] as? String)
```

File: app/src/androidTest/java/com/sdp13epfl2021/projmag/database/UserProfileDatabaseTest.kt [hunk 8]
```diff
@@ -113,9 +113,9 @@ class UserProfileDatabaseTest {
     @Test
     fun checkThatGettingProfileWorks() {
         val udb = UserProfileDatabase(mockFirebaseFirestore, mockFirebaseAuth)
-        udb.getProfile {
+        udb.getProfile({
             assert(it != null)
```
Comment (arnauds5) [inline app/src/androidTest/java/com/sdp13epfl2021/projmag/database/UserProfileDatabaseTest.kt]: Using an assertEquals would be better than just null. (need to add "data" to the ImmutableProfile class)
`assertEquals(exampleUserProfile, it)`

**Review by arnauds5 — CHANGES_REQUESTED** [review]
One of the reason that the tests failed is that age/sciper are not Long in profile (Int), only from firestore(Long) => need to add ?.toLong() for these.
```
Mockito.`when`(mockDS["age"]).thenReturn(exampleUserProfile?.age?.toLong())
Mockito.`when`(mockDS["sciper"]).thenReturn(exampleUserProfile?.sciper?.toLong())
```

File: app/src/androidTest/java/com/sdp13epfl2021/projmag/database/UserProfileDatabaseTest.kt (hunk 8 above)
Comment (asfoury) [reply app/src/androidTest/java/com/sdp13epfl2021/projmag/database/UserProfileDatabaseTest.kt]: Indeed thats much better

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 7 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: Good catch I fixed it

File: .idea/compiler.xml [hunk 9]
```diff
@@ -1,6 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <project version="4">
   <component name="CompilerConfiguration">
-    <bytecodeTargetLevel target="1.8" />
+    <bytecodeTargetLevel target="11" />
```
Comment (PaulCoral) [inline .idea/compiler.xml:4]: .idea/ files are not needed

File: .idea/misc.xml [hunk 10]
```diff
@@ -1,6 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <project version="4">
-  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
+  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
```
Comment (PaulCoral) [inline .idea/misc.xml:3]: idem

File: .idea/runConfigurations.xml [hunk 11]
```diff
@@ -0,0 +1,10 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<project version="4">
+  <component name="RunConfigurationProducerService">
+    <option name="ignoredProducers">
+      <set>
+        <option value="com.android.tools.idea.compose.preview.runconfiguration.ComposePreviewRunConfigurationProducer" />
+      </set>
+    </option>
+  </component>
+</project>
```
Comment (PaulCoral) [inline .idea/runConfigurations.xml:10]: idem

File: app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt [hunk 12]
```diff
@@ -35,21 +31,18 @@ class ProfilePageActivity : AppCompatActivity() {
...
             findViewById<TextView>(R.id.profile_sciper).setVisibility(View.INVISIBLE)
-            buttonAddCv.setVisibility(View.INVISIBLE)
-        }
-        button.setOnClickListener {
-            startActivityForResult(Intent(Intent.ACTION_PICK, MediaStore.Images.Media.INTERNAL_CONTENT_URI), pickImage)
+            //buttonAddCv.setVisibility(View.INVISIBLE)
         }
 
+        UserProfileDatabase(Firebase.firestore, Firebase.auth).getProfile(::loadUserProfile) {
+            Toast.makeText(this, "Failed to load profile", Toast.LENGTH_LONG).show()
```
Comment (PaulCoral) [inline app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt]: This could be a string resource

File: app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt [hunk 13]
```diff
@@ -78,7 +71,7 @@ class ProfilePageActivity : AppCompatActivity() {
             findViewById<EditText>(R.id.profile_phone_number).setText(profile.phoneNumber)
             findViewById<EditText>(R.id.profile_sciper).setText(profile.sciper.toString())
         } else {
-            Log.d(ContentValues.TAG, "NULL")
+            Toast.makeText(this, "Failed to load profile", Toast.LENGTH_LONG).show()
```
Comment (PaulCoral) [inline app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt]: also a string resource
And as it is the same toast message you could save it and just call `show()` on it to avoid duplication

File: app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt [hunk 14]
```diff
@@ -95,9 +88,11 @@ class ProfilePageActivity : AppCompatActivity() {
...
         val age = findViewById<EditText>(R.id.profile_age).text.toString()
-        val gender = if (findViewById<EditText>(R.id.profile_genre).text.toString() == Gender.MALE.toString())  Gender.MALE
-        else {
-            if (findViewById<EditText>(R.id.profile_genre).text.toString() == Gender.FEMALE.toString()) Gender.FEMALE else Gender.OTHER
+
+        val gender = when(findViewById<EditText>(R.id.profile_genre).text.toString()){
+            Gender.MALE.name -> Gender.MALE
+            Gender.FEMALE.name -> Gender.FEMALE
+            else -> Gender.OTHER
         }
```
Comment (PaulCoral) [inline app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt:95]: this is a lot cleaner with this `when` operator :+1:

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt [hunk 15]
```diff
@@ -55,74 +61,67 @@ class UserProfileDatabase(
...
-                        val lastName = document["lastName"] as? String
-                        val ageLong = document["age"]
+                        val firstName = (document["firstName"] as? String)
+                        val lastName = (document["lastName"] as? String)
+                        val age = (document["age"] as? Long)?.toInt()
+                        val sciper = (document["sciper"] as? Long)?.toInt()
+                        val phoneNumber = (document["phoneNumber"] as? String)
 
-                        val gender = when (document["gender"] as? String) {
+                        val gender = when ((document["gender"] as? String)) {
```
Comment (PaulCoral) [inline app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: why the parenthesis?

**Review by PaulCoral — APPROVED** [review]
Globally it is good. I added a few notes

File: app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt (hunk 12 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt]: I agree

File: app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt (hunk 13 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/activities/ProfilePageActivity.kt]: I agree

File: app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt (hunk 15 above)
Comment (asfoury) [reply app/src/main/java/com/sdp13epfl2021/projmag/database/UserProfileDatabase.kt]: Indeed there is no need for them I will remove them

**Review by arnauds5 — APPROVED** [review]
